import type { Metadata } from "next";
import { inter } from "@/config/fonts";

import "./globals.css";
import { Provider } from "@/providers/session-provider/Provider";
import { PayPalProvider } from "@/providers/paypal-provider/PayPalProvider";
import AlertMessageProvider from "@/providers/alert-message-provider/AlertMessageProvider";

export const metadata: Metadata = {
  title: {
    template: "%s - E-COMMERS | Shop",
    default: "E-COMMERS | Shop",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PayPalProvider>
          <AlertMessageProvider>
            <Provider>{children}</Provider>
          </AlertMessageProvider>
        </PayPalProvider>
      </body>
    </html>
  );
}
