export const ROUTES = {
  ROOT: "/",
  CATEGORY: "/category",
  MEN: "/category/men",
  WOMEN: "/category/women",
  CHILDREN: "/category/kid",
  SEARCH: "/search/",
  CART: "/cart/",
  PRODUCT: "/product/",
  CHECKOUT: "/checkout/",
  ADDRESS: "/checkout/address",
  ORDERS: "/orders/",
  ADMIN_ORDERS: "/admin/orders/",
  ADMIN_USERS: "/admin/users/",
  ADMIN_PRODUCT: "/admin/product/",
  ADMIN_PRODUCTS: "/admin/products/",
  EMPTY: "/empty/",
  LOGIN: "/auth/login/",
  NEW_ACCOUNT: "/auth/new-account/",
  PROFILE: "/profile"
};
